# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kamila reads
author: Kamila Komisarek
email: kamila.nowak88@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-122220444-1
user_description: To jest moje description.

instagram_username: kamilareads

languages: ["en", "pl"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: false

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
plugins:
  - jemoji

author_trans:
  en: Author
  pl: Autor

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# git checkout site
# rm -rf _site

# $ JEKYLL_ENV=production bundle exec jekyll build
#git add --all
#git commit -m "`date`"
#git push origin site
#git subtree push --prefix  _site/ origin gh-pages
exclude: ['package.json', 'src', 'node_modules']
